apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/vholubiuk/fleet-commander.git
    targetRevision: main
    path: argocd

    directory:
      recurse: false
      include: "*-application.yaml"
      exclude: "root-application.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true