name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/fleet-commander

jobs:
  docker-build:
    name: Build, test and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build -t fleet-commander:ci ./app

      - name: Run container
        run: docker run -d --name fleet-commander -p 8000:8080 fleet-commander:ci

      - name: Test health endpoint
        run: |
          sleep 5
          curl --fail http://localhost:8000/health

      - name: Show container logs on failure
        if: failure()
        run: docker logs fleet-commander

      - name: Login to GHCR
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker image
        if: github.event_name == 'push'
        run: |
          docker tag fleet-commander:ci $IMAGE_NAME:${{ github.sha }}
          docker tag fleet-commander:ci $IMAGE_NAME:latest

      - name: Push Docker image to GHCR
        if: github.event_name == 'push'
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest